--> Nome: Lucas Garcia
--> RM: 554070

--> CREATE TABLES
CREATE TABLE ENTREGA(
    ID_ENTREGA NUMBER(10) PRIMARY KEY,
    STATUS_ENTREGA VARCHAR2(20) NOT NULL,
    DATA_SAIDA DATE NOT NULL,
    OBSERVACOES VARCHAR2(255) NOT NULL,
    ID_PEDIDO NUMBER(10), 
    ID_ENTREGADOR NUMBER(10)  
);

CREATE TABLE ENTREGADOR(
    ID_ENTREGADOR NUMBER(10) PRIMARY KEY, 
    NOME VARCHAR2(100) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    VEICULO VARCHAR2(50) NOT NULL,
    PLACA_VEICULO VARCHAR2(10) NOT NULL
);

CREATE TABLE PEDIDO(
    ID_PEDIDO NUMBER(10) PRIMARY KEY,
    DATA_PEDIDO DATE NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    TOTAL NUMBER(10, 2) NOT NULL,
    ENDERECO_ENTREGA VARCHAR2(255) NOT NULL,
    ID_CLIENTE NUMBER(10),  
    ID_FUNCIONARIO NUMBER(10)  
);

CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    ENDERECO VARCHAR2(255) NOT NULL,
    DATA_CADASTRO DATE NOT NULL
);

CREATE TABLE FUNCIONARIO(
    ID_FUNCIONARIO NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    CARGO VARCHAR2(50) NOT NULL,
    DATA_ADMISSAO DATE NOT NULL,
    SALARIO NUMBER(10, 2) NOT NULL
);

CREATE TABLE PAGAMENTO(
    ID_PAGAMENTO NUMBER(10) PRIMARY KEY,
    TIPO_PAGAMENTO VARCHAR2(50) NOT NULL,
    STATUS_PAGAMENTO VARCHAR2(50) NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    VALOR_PAGO NUMBER(10, 2) NOT NULL,
    ID_PEDIDO NUMBER(10)  
);

CREATE TABLE ITENS_PEDIDO(
    ID_ITEM NUMBER(10) PRIMARY KEY,
    QUANTIDADE NUMBER NOT NULL,
    PRECO_UNITARIO NUMBER(10, 2) NOT NULL,
    ID_PEDIDO NUMBER(10),  
    ID_PRODUTO NUMBER(10) 
);

CREATE TABLE PRODUTO(
    ID_PRODUTO NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(255) NOT NULL,
    PRECO NUMBER(10, 2),
    ESTOQUE NUMBER,
    CATEGORIA VARCHAR2(50),
    IMAGEM_URL VARCHAR2(255)
);

--> FOREIGN KEYS
ALTER TABLE ENTREGA ADD CONSTRAINT FK_PEDIDO_ENTREGA FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);
ALTER TABLE ENTREGA ADD CONSTRAINT FK_ENTREGADOR FOREIGN KEY(ID_ENTREGADOR) REFERENCES ENTREGADOR(ID_ENTREGADOR);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO);

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PEDIDO_PAGAMENTO FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_PEDIDO_ITENS FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);
ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO);


--> INSERTS
INSERT INTO CLIENTE (ID_CLIENTE, NOME, EMAIL, TELEFONE, ENDERECO, DATA_CADASTRO) 
VALUES (1, 'Lucas Garcia', 'lucasgarcia@gmail.com', '(11) 959665055', 'São Paulo, SP', TO_DATE('2024-03-15', 'YYYY-MM-DD'));

INSERT INTO ENTREGADOR (ID_ENTREGADOR, NOME, TELEFONE, VEICULO, PLACA_VEICULO) 
VALUES (1, 'Lucas Garcia', '(11) 959665055', 'Moto Honda CG 160', 'ABC1D23');

INSERT INTO FUNCIONARIO (ID_FUNCIONARIO, NOME, EMAIL, TELEFONE, CARGO, DATA_ADMISSAO, SALARIO) 
VALUES (554070, 'Lucas Garcia', 'lucasgarcia@gmail.com', '(11) 959665055', 'Data Scientist', TO_DATE('2023-01-10', 'YYYY-MM-DD'), 8500.00);

INSERT INTO PEDIDO (ID_PEDIDO, DATA_PEDIDO, STATUS, TOTAL, ENDERECO_ENTREGA, ID_CLIENTE, ID_FUNCIONARIO) 
VALUES (1001, TO_DATE('2024-03-18', 'YYYY-MM-DD'), 'Em andamento', 199.90, 'Av. Paulista, São Paulo, SP', 1, 554070);

INSERT INTO ENTREGA (ID_ENTREGA, STATUS_ENTREGA, DATA_SAIDA, OBSERVACOES, ID_PEDIDO, ID_ENTREGADOR) 
VALUES (5001, 'Saiu para entrega', TO_DATE('2024-03-18', 'YYYY-MM-DD'), 'Entregar no horário comercial', 1001, 1);

INSERT INTO PAGAMENTO (ID_PAGAMENTO, TIPO_PAGAMENTO, STATUS_PAGAMENTO, DATA_PAGAMENTO, VALOR_PAGO, ID_PEDIDO) 
VALUES (3001, 'Cartão de Crédito', 'Aprovado', TO_DATE('2024-03-17', 'YYYY-MM-DD'), 199.90, 1001);

INSERT INTO PRODUTO (ID_PRODUTO, NOME, DESCRICAO, PRECO, ESTOQUE, CATEGORIA, IMAGEM_URL) 
VALUES (2001, 'Smartphone X', 'Tela de 6.5", 128GB', 1999.99, 50, 'Eletrônicos', 'https://produto.com/smartphone.jpg');

INSERT INTO ITENS_PEDIDO (ID_ITEM, QUANTIDADE, PRECO_UNITARIO, ID_PEDIDO, ID_PRODUTO) 
VALUES (4001, 1, 1999.99, 1001, 2001);

--> SELECT
SELECT * FROM CLIENTE;