CREATE TABLE ALUNO	(
					RM_ALUNO	NUMBER(10),
					NM_ALUNO	VARCHAR2(20),
					STATUS		CHAR(1)
					);



SALARIO NUMBER(8,2)
10000000.00
100000.00					
5000.00


CREATE TABLE ALUNO_ES	(
					RM_ALUNO	NUMBER(10),
					NM_ALUNO	VARCHAR2(20),
					STATUS		CHAR(1)
					);
ALTER TABLE ALUNO_ES
ADD CONSTRAINT PK_ALUNO_ES
PRIMARY KEY (RM_ALUNO);
                    
INSERT INTO ALUNO_ES VALUES(1,'JOAZINHO','A');
INSERT INTO ALUNO_ES VALUES(2,'MARIAZINHA','A');
INSERT INTO ALUNO_ES VALUES(3,'LUIZINHO','A');
INSERT INTO ALUNO_ES VALUES(4,'HUGUINHO','A');
COMMIT;
SELECT * FROM ALUNO_ES;
DESC  ALUNO_ES;   
ROLLBACK;
DELETE ALUNO_ES;

UPDATE ALUNO_ES
SET RM_ALUNO =3
WHERE NM_ALUNO = 'LUIZINHO';
                    